apiVersion: batch/v1
kind: Job
metadata:
  name: upload-html
spec:
  template:
    spec:
      containers:
      - name: uploader
        image: busybox
        command: ["/bin/sh", "-c"]
        args:
        - echo "<h1>Hello from NFS!</h1>" > /mnt/nfs/index.html;
        volumeMounts:
        - name: web-content
          mountPath: /mnt/nfs
      restartPolicy: OnFailure
      volumes:
      - name: web-content
        persistentVolumeClaim:
          claimName: web-content-pvc  